name: knowledge-base-dev

services:
    worker:
        build:
            context: .
            dockerfile: docker/worker/Dockerfile.dev
        container_name: kb-dev-worker
        env_file: .env.local
        environment:
            - DATABASE_URL=postgresql://postgres:dev_password@postgres:5432/knowledge_base
            - REDIS_URL=redis://:dev_redis_password@redis:6379
            - MINIO_ENDPOINT=minio
            - GOTENBERG_URL=http://gotenberg:3001
        volumes:
            - ./src:/app/src
            - ./scripts:/app/scripts
            - ./prisma:/app/prisma
        command: pnpm dev:worker
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
        networks:
            - kb-network
