name: knowledge-base

services:
    postgres:
        env_file:
            - .env.local
        ports: ['5432:5432']
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-knowledge_base}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_password}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-knowledge_base}',
                ]
            interval: 10s
            timeout: 5s
            retries: 5

    minio:
        env_file:
            - .env.local
        ports: ['9000:9000', '9001:9001']
        healthcheck:
            test:
                ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
        volumes:
            - minio_data:/data

    redis:
        env_file:
            - .env.local
        ports: ['6379:6379']
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
        volumes:
            - redis_data:/data

    gotenberg:
        env_file:
            - .env.local
        ports: ['3001:3000']
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']

volumes:
    postgres_data:
    minio_data:
    redis_data:
    gotenberg_data:
