# name: knowledge-base-dev

# services:
#     postgres:
#         container_name: kb-dev-postgres
#         env_file: .env.local

#     minio:
#         container_name: kb-dev-minio
#         env_file: .env.local

#     redis:
#         container_name: kb-dev-redis
#         env_file: .env.local

#     gotenberg:
#         container_name: kb-dev-gotenberg

#     worker:
#         container_name: kb-dev-worker
#         build:
#             context: .
#             dockerfile: docker/worker/Dockerfile
#         env_file:
#             - .env.local
#         volumes:
#             - ./src:/app/src
#             - ./scripts:/app/scripts
#             - ./prisma:/app/prisma
#         depends_on:
#             - postgres
#             - redis

name: knowledge-base-dev

services:
    worker:
        build:
            context: .
            dockerfile: docker/worker/Dockerfile.dev
        container_name: kb-dev-worker
        env_file: .env.local
        environment:
            - DATABASE_URL=postgresql://postgres:dev_password@postgres:5432/knowledge_base
            - REDIS_URL=redis://:dev_redis_password@redis:6379
            - MINIO_ENDPOINT=minio
            - GOTENBERG_URL=http://gotenberg:3001
        volumes:
            - ./src:/app/src
            - ./scripts:/app/scripts
            - ./prisma:/app/prisma
        command: pnpm dev:worker
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
        networks:
            - kb-network

